working now in Debian, haven't het tested on iSH

diff --git a/abuild.in b/abuild.in
--- a/abuild.in
+++ b/abuild.in
@@ -1,4 +1,4 @@
-#!/bin/ash -e
+#!/bin/ash
 # vim: set filetype=sh:
 
 # abuild - build apk packages (light version of makepkg)
@@ -8,6 +8,14 @@
 # Distributed under GPL-2.0-only
 #
 
+if [ -z "$BB_ASH_VERSION" ]; then
+# `ash` on Alpine has advanced constructs such as ${string:0:8} that aren't
+# present on Debian ash. We check for this and re-run with Bash if not found.
+	if [ -z "$BASH_VERSION" ]; then
+		exec bash -x $0 "$@"
+	fi
+fi
+set -e  # now turn on error abort
 program_version=@VERSION@
 sharedir=${ABUILD_SHAREDIR:-@sharedir@}
 
